apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: prefect-server
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: prefect-server
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: kube-ingress
      ports:
        - protocol: TCP
          port: 4200

    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: prefect-worker

      ports:
        - protocol: TCP
          port: 4200

    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: prefect-job

      ports:
        - protocol: TCP
          port: 4200

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.names.fullname" . }}-postgresql
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: primary
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/name: postgresql
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: prefect-server
      ports:
        - protocol: TCP
          port: 5432