apiVersion: v1
kind: Secret
metadata:
  name: prefect-config
  namespace: fairtracks-ns10022k
  labels:
    app: prefect
type: Opaque
data:
  api_key: RlFtR05rTTZOVC1jbXRYCg== #  Encode 'not so secure' api key to base64
  api_url: aHR0cDovL3ByZWZlY3QuZmFpcnRyYWNrcy5zaWdtYTIubm8vYXBpCg== # Our API service inside the K8S cluster. Encode to b64
#  api_external: OUR_EXTERNAL_URL # Self explained. Encode to b64
#  api_db: postgresql+asyncpg://prefect:SECRET_PWD@postgres-server:5432/prefectdb # Again, encode it to base64 with a proper credentials
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prefect-login-auth
  namespace: fairtracks-ns10022k
  labels:
    app: prefect
data:
  auth: YWRtaW46JGFwcjEkdDNhLzJvalAkYlZKc3lJUW9EeXdVQXUyM3o2cDF2MQo= # Generate bcrypted htpassword for UI and encode it again to b64.