## Common parameters
# -- partially overrides common.names.name
nameOverride: ""
# -- fully override common.names.fullname
fullnameOverride: "prefect-worker"
# -- fully override common.names.namespace
namespaceOverride: ""
# -- labels to add to all deployed objects
commonLabels: {}
# -- annotations to add to all deployed objects
commonAnnotations: {}

## Deployment Configuration
worker:
  autoscaling:
    # -- enable autoscaling for the worker
    enabled: false
    # -- minimum number of replicas to scale down to
    minReplicas: 1
    # -- maximum number of replicas to scale up to
    maxReplicas: 1
    # -- target CPU utilization percentage for scaling the worker
    targetCPUUtilizationPercentage: 80
    # -- target memory utilization percentage for scaling the worker
    targetMemoryUtilizationPercentage: 80

  # -- unique cluster identifier, if none is provided this value will be infered at time of helm install
  clusterUid: ""

  initContainer:
    # -- the resource specifications for the sync-base-job-template initContainer
    # Defaults to the resources defined for the worker container
    resources: {}
      # -- the requested resources for the sync-base-job-template initContainer
      # requests:
      #   memory: 256Mi
      #   cpu: 100m
      # -- the requested limits for the sync-base-job-template initContainer
      # limits:
      #   memory: 1Gi
      #   cpu: 1000m
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
    # -- security context for the sync-base-job-template initContainer
    containerSecurityContext:
      # -- set init containers' security context runAsUser
      runAsUser: 1001
      # -- set init containers' security context runAsNonRoot
      runAsNonRoot: true
      # -- set init containers' security context readOnlyRootFilesystem
      readOnlyRootFilesystem: true
      # -- set init containers' security context allowPrivilegeEscalation
      allowPrivilegeEscalation: false
      # -- set init container's security context capabilities
      capabilities: {}

  image:
    # -- worker image repository
    repository: fairtracks/omnipy-examples
    ## prefect tag is pinned to the latest available image tag at packaging time.  Update the value here to
    ## override pinned tag
    # -- prefect image tag (immutable tags are recommended)
    prefectTag: v0.7.7
    # -- worker image pull policy
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    # -- worker image pull secrets
    pullSecrets: []
    # -- enable worker image debug mode
    debug: false

  ## general configuration of the worker
  config:
    # -- the work pool that your started worker will poll.
    workPool: "omnipy"
    # -- one or more work queue names for the worker to pull from. if not provided, the worker will pull from all work queues in the work pool
    workQueues: []
    # -- how often the worker will query for runs
    queryInterval: 5
    # -- when querying for runs, how many seconds in the future can they be scheduled
    prefetchSeconds: 10
    # -- connect using HTTP/2 if the server supports it (experimental)
    http2: true
    ## You can set the worker type here.
    ## The default image includes only the type "kubernetes".
    ## Custom workers must be properly registered with the prefect cli.
    ## See the guide here: https://docs.prefect.io/2.11.3/guides/deployment/developing-a-new-worker-type/
    # -- specify the worker type
    type: kubernetes
    ## one of 'always', 'if-not-present', 'never', 'prompt'
    # --  install policy to use workers from Prefect integration packages.
    installPolicy: prompt
    # -- the name to give to the started worker. If not provided, a unique name will be generated.
    name: null
    # -- maximum number of flow runs to start simultaneously (default: unlimited)
    limit: null

    ##  If unspecified, Prefect will use the default base job template for the given worker type. If the work pool already exists, this will be ignored.
    ## e.g.:
    ## baseJobTemplate:
    ##   configuration: |
    ##    {
    ##      "variables": {
    ##        ...
    ##      },
    ##      "job_configuration": {
    ##        ...
    ##      }
    ##    }
    ## OR
    ## baseJobTemplate:
    ##   existingConfigMapName: "my-existing-config-map"

    baseJobTemplate:
      # -- the name of an existing ConfigMap containing a base job template. NOTE - the key must be 'baseJobTemplate.json'
      existingConfigMapName: ""
      # -- JSON formatted base job template. If data is provided here, the chart will generate a configmap and mount it to the worker pod
#      configuration: null
      configuration: >
        {
          "job_configuration": {
            "command": "{{ command }}",
            "env": "{{ env }}",
            "labels": "{{ labels }}",
            "name": "{{ name }}",
            "namespace": "{{ namespace }}",
            "job_manifest": {
              "apiVersion": "batch/v1",
              "kind": "Job",
              "metadata": {
                "labels": "{{ labels }}",
                "namespace": "{{ namespace }}",
                "generateName": "{{ name }}-"
              },
              "resources": {

              },
              "spec": {
                "backoffLimit": 0,
                "ttlSecondsAfterFinished": "{{ finished_job_ttl }}",
                "template": {
                  "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "restartPolicy": "Never",
                    "serviceAccountName": "{{ service_account_name }}",
                    "containers": [
                      {
                        "name": "prefect-job",
                        "env": "{{ env }}",
                        "image": "{{ image }}",
                        "imagePullPolicy": "{{ image_pull_policy }}",
                        "args": "{{ command }}",
                        "resources": {
                          "requests": {
                            "cpu": "{{ cpu_request }}",
                            "memory": "{{ memory_request }}"
                          }
                        }
                      }
                    ]
                  }
                }
              }
            },
            "cluster_config": "{{ cluster_config }}",
            "job_watch_timeout_seconds": "{{ job_watch_timeout_seconds }}",
            "pod_watch_timeout_seconds": "{{ pod_watch_timeout_seconds }}",
            "stream_output": "{{ stream_output }}"
          },
          "variables": {
            "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template.",
            "type": "object",
            "properties": {
              "name": {
                "title": "Name",
                "description": "Name given to infrastructure created by a worker.",
                "type": "string"
              },
              "env": {
                "title": "Environment Variables",
                "description": "Environment variables to set when starting a flow run.",
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "labels": {
                "title": "Labels",
                "description": "Labels applied to infrastructure created by a worker.",
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "command": {
                "title": "Command",
                "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker.",
                "type": "string"
              },
              "namespace": {
                "title": "Namespace",
                "description": "The Kubernetes namespace to create jobs within.",
                "default": "default",
                "type": "string"
              },
              "image": {
                "title": "Image",
                "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used.",
                "example": "docker.io/prefecthq/prefect:2-latest",
                "default": "fairtracks/omnipy-examples:v0.7.7",
                "type": "string"
              },
              "service_account_name": {
                "title": "Service Account Name",
                "description": "The Kubernetes service account to use for job creation.",
                "type": "string"
              },
              "image_pull_policy": {
                "title": "Image Pull Policy",
                "description": "The Kubernetes image pull policy to use for job containers.",
                "default": "IfNotPresent",
                "enum": [
                  "IfNotPresent",
                  "Always",
                  "Never"
                ],
                "type": "string"
              },
              "finished_job_ttl": {
                "title": "Finished Job TTL",
                "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely.",
                "type": "integer"
              },
              "job_watch_timeout_seconds": {
                "title": "Job Watch Timeout Seconds",
                "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely.",
                "type": "integer"
              },
              "pod_watch_timeout_seconds": {
                "title": "Pod Watch Timeout Seconds",
                "description": "Number of seconds to watch for pod creation before timing out.",
                "default": 60,
                "type": "integer"
              },
              "stream_output": {
                "title": "Stream Output",
                "description": "If set, output will be streamed from the job to local standard output.",
                "default": true,
                "type": "boolean"
              },
              "cluster_config": {
                "title": "Cluster Config",
                "description": "The Kubernetes cluster config to use for job creation.",
                "allOf": [
                  {
                    "$ref": "#/definitions/KubernetesClusterConfig"
                  }
                ]
              },
              "cpu_request": {
                "title": "CPU Request",
                "description": "The CPU allocation to request for this pod.",
                "default": "1",
                "type": "string"
              },
              "memory_request": {
                "title": "Memory Request",
                "description": "The memory allocation to request for this pod.",
                "default": "2G",
                "type": "string"
              }
            },
            "definitions": {
              "KubernetesClusterConfig": {
                "title": "KubernetesClusterConfig",
                "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
                "type": "object",
                "properties": {
                  "config": {
                    "title": "Config",
                    "description": "The entire contents of a kubectl config file.",
                    "type": "object"
                  },
                  "context_name": {
                    "title": "Context Name",
                    "description": "The name of the kubectl context to use.",
                    "type": "string"
                  }
                },
                "required": [
                  "config",
                  "context_name"
                ],
                "block_type_slug": "kubernetes-cluster-config",
                "secret_fields": [ ],
                "block_schema_references": { }
              }
            }
          }
        }
      # -- optionally override the default name of the generated configmap
      # name: ""


  ## connection settings
  # -- one of 'cloud', 'selfHosted', or 'server'
  apiConfig: "server"

  cloudApiConfig:
    # -- prefect account ID
    accountId: ""
    # -- prefect workspace ID
    workspaceId: ""

    apiKeySecret:
      # -- prefect API secret name
      name: prefect-api-key
      # -- prefect API secret key
      key: key

    # -- prefect cloud API url; the full URL is constructed as https://cloudUrl/accounts/accountId/workspaces/workspaceId
    cloudUrl: https://api.prefect.cloud/api

  selfHostedCloudApiConfig:
    # -- prefect API url (PREFECT_API_URL)
    apiUrl: ""
    # -- prefect account ID
    accountId: ""
    # -- prefect workspace ID
    workspaceId: ""

    apiKeySecret:
      # -- prefect API secret name
      name: prefect-api-key
      # -- prefect API secret key
      key: key
    # -- self hosted UI url
    uiUrl: ""

  serverApiConfig:
    # If the prefect server is located external to this cluster, set a fully qualified domain name as the apiUrl
    # If the prefect server pod is deployed to this cluster, use the cluster DNS endpoint: http://<prefect-server-service-name>.<namespace>.svc.cluster.local:<prefect-server-port>/api
    # -- prefect API url (PREFECT_API_URL)
#    apiUrl: "http://localhost:4200/api"
#    apiUrl: "http://192.168.64.6:4200/api"
#    apiUrl: "http://prefect-server:4200/api"
    apiUrl: "http://prefect-server.default.svc.cluster.local:4200/api"
    # -- prefect UI url
    uiUrl: http://prefect.local:32007

  # -- number of worker replicas to deploy
  replicaCount: 2

  resources:
    # -- the requested resources for the worker container
    requests:
      memory: 256Mi
      cpu: 100m
    # -- the requested limits for the worker container
    limits:
      memory: 1Gi
      cpu: 1000m

  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    enabled: false
    config:
      # -- The number of seconds to wait before starting the first probe.
      initialDelaySeconds: 10
      # -- The number of seconds to wait between consecutive probes.
      periodSeconds: 10
      # -- The number of seconds to wait for a probe response before considering it as failed.
      timeoutSeconds: 5
      # -- The number of consecutive failures allowed before considering the probe as failed.
      failureThreshold: 3
      # -- The minimum consecutive successes required to consider the probe successful.
      successThreshold: 1

  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  podSecurityContext:
    # -- set worker pod's security context runAsUser
    runAsUser: 1001
    # -- set worker pod's security context runAsNonRoot
    runAsNonRoot: true
    # -- set worker pod's security context fsGroup
    fsGroup: 1001

  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
  # -- priority class name to use for the worker pods; if the priority class is empty or doesn't exist, the worker pods are scheduled without a priority class
  priorityClassName: ""

  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  containerSecurityContext:
    # -- set worker containers' security context runAsUser
    runAsUser: 1001
    # -- set worker containers' security context runAsNonRoot
    runAsNonRoot: true
    # -- set worker containers' security context readOnlyRootFilesystem
    readOnlyRootFilesystem: true
    # -- set worker containers' security context allowPrivilegeEscalation
    allowPrivilegeEscalation: false
    # -- set worker container's security context capabilities
    capabilities: {}

  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  # -- extra labels for worker pod
  podLabels: {}

  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  # -- extra annotations for worker pod
  podAnnotations: {}

  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # -- affinity for worker pods assignment
  affinity: {}

  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  # -- node labels for worker pods assignment
  nodeSelector:
    role: worker

  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # -- tolerations for worker pods assignment
  tolerations: []

  ## List of extra env vars
  ## e.g:
  ## extraEnvVars:
  ##   - name: FOO
  ##     value: "bar"
  # -- array with extra environment variables to add to worker nodes  extraEnvVars:
  extraEnvVars:
    - name: PREFECT_SERVER_ANALYTICS_ENABLED
      value: "false"
#    - name: PREFECT_API_KEY
#      valueFrom:
#        secretKeyRef:
#          name: prefect-config
#          key: api_key

  # -- name of existing ConfigMap containing extra env vars to add to worker nodes
  extraEnvVarsCM: ""

  # -- name of existing Secret containing extra env vars to add to worker nodes
  extraEnvVarsSecret: ""

  # -- additional sidecar containers
  extraContainers: []

  # -- array with extra volumes for the worker pod
  extraVolumes: []

  # -- array with extra volumeMounts for the worker pod
  extraVolumeMounts: []

  # -- array with extra Arguments for the worker container to start with
  extraArgs: []

## ServiceAccount configuration
serviceAccount:
  # -- specifies whether a ServiceAccount should be created
  create: true
  # -- the name of the ServiceAccount to use. if not set and create is true, a name is generated using the common.names.fullname template
  name: ""
  # -- additional service account annotations (evaluated as a template)
  annotations: {}

## Role configuration
role:
  # -- specifies whether a Role should be created
  create: true
  ## List of extra role permissions
  ## e.g:
  ## extraPermissions:
  ##  - apiGroups: [""]
  ##    resources: ["pods", "services"]
  ##    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # -- array with extra permissions to add to the worker role
  extraPermissions:
    - apiGroups: [""]
      resources: ["pods", "services"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["get", "list", "watch"]

## RoleBinding configuration
rolebinding:
  # -- specifies whether a RoleBinding should be created
  create: true
